// <auto-generated />
using System;
using HayvanSahiplenmeSitesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HayvanSahiplenmeSitesi.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Cins", b =>
                {
                    b.Property<int>("CinsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CinsAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HayvanID1")
                        .HasColumnType("int");

                    b.HasKey("CinsID");

                    b.HasIndex("HayvanID1");

                    b.ToTable("Cins");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Hayvan", b =>
                {
                    b.Property<int>("HayvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HayvanID");

                    b.ToTable("Hayvan");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Ilan", b =>
                {
                    b.Property<int>("IlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AsiDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CinsID1")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Fotograf")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HayvanID1")
                        .HasColumnType("int");

                    b.Property<int?>("IlanSahibiID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("IlanID");

                    b.HasIndex("CinsID1");

                    b.HasIndex("HayvanID1");

                    b.HasIndex("IlanSahibiID1");

                    b.ToTable("Ilan");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.IlanSahibi", b =>
                {
                    b.Property<int>("IlanSahibiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TelNo")
                        .HasColumnType("int");

                    b.HasKey("IlanSahibiID");

                    b.ToTable("IlanSahibi");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Cins", b =>
                {
                    b.HasOne("HayvanSahiplenmeSitesi.Models.Hayvan", "HayvanID")
                        .WithMany("Cinss")
                        .HasForeignKey("HayvanID1");

                    b.Navigation("HayvanID");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Ilan", b =>
                {
                    b.HasOne("HayvanSahiplenmeSitesi.Models.Cins", "CinsID")
                        .WithMany("Ilans")
                        .HasForeignKey("CinsID1");

                    b.HasOne("HayvanSahiplenmeSitesi.Models.Hayvan", "HayvanID")
                        .WithMany("Ilans")
                        .HasForeignKey("HayvanID1");

                    b.HasOne("HayvanSahiplenmeSitesi.Models.IlanSahibi", "IlanSahibiID")
                        .WithMany("Ilan")
                        .HasForeignKey("IlanSahibiID1");

                    b.Navigation("CinsID");

                    b.Navigation("HayvanID");

                    b.Navigation("IlanSahibiID");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Cins", b =>
                {
                    b.Navigation("Ilans");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.Hayvan", b =>
                {
                    b.Navigation("Cinss");

                    b.Navigation("Ilans");
                });

            modelBuilder.Entity("HayvanSahiplenmeSitesi.Models.IlanSahibi", b =>
                {
                    b.Navigation("Ilan");
                });
#pragma warning restore 612, 618
        }
    }
}
